
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: Mill Creek Insurance Agency
subtitle: "New York State Insurnace Agency"
url: "https://www.millcreekagency.com"
baseurl: ""
cover: ""
logo: ""
cyber_program_url: "/assets/CyberPolicy.pdf"

# Build settings
markdown: kramdown

# Category descriptions (for archive pages)
defaults:
  - scope:
      path: "assets/"
    values:
      pdf: true

plugins:
  - jekyll-redirect-from
